{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "cannot import name 'UuidRepresentation' from 'bson.binary' (c:\\Users\\keshg\\anaconda3\\Lib\\site-packages\\bson\\binary.py)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[16], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m MongoClient\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mssl\u001b[39;00m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;66;03m# MongoDB connection URI\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\keshg\\anaconda3\\Lib\\site-packages\\pymongo\\__init__.py:90\u001b[0m\n\u001b[0;32m     82\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmongo_replica_set_client\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m MongoReplicaSetClient\n\u001b[0;32m     83\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01moperations\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (IndexModel,\n\u001b[0;32m     84\u001b[0m                                 InsertOne,\n\u001b[0;32m     85\u001b[0m                                 DeleteOne,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     88\u001b[0m                                 UpdateMany,\n\u001b[0;32m     89\u001b[0m                                 ReplaceOne)\n\u001b[1;32m---> 90\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mread_preferences\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ReadPreference\n\u001b[0;32m     91\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mwrite_concern\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m WriteConcern\n\u001b[0;32m     93\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mhas_c\u001b[39m():\n",
      "File \u001b[1;32mc:\\Users\\keshg\\anaconda3\\Lib\\site-packages\\pymongo\\collection.py:38\u001b[0m\n\u001b[0;32m     36\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mchange_stream\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ChangeStream\n\u001b[0;32m     37\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcursor\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Cursor, RawBatchCursor\n\u001b[1;32m---> 38\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01merrors\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (BulkWriteError,\n\u001b[0;32m     39\u001b[0m                             ConfigurationError,\n\u001b[0;32m     40\u001b[0m                             InvalidName,\n\u001b[0;32m     41\u001b[0m                             OperationFailure)\n\u001b[0;32m     42\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mhelpers\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (_check_write_command_response,\n\u001b[0;32m     43\u001b[0m                              _raise_last_error)\n\u001b[0;32m     44\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmessage\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m _UNICODE_REPLACE_CODEC_OPTIONS\n",
      "File \u001b[1;32mc:\\Users\\keshg\\anaconda3\\Lib\\site-packages\\bson\\__init__.py:89\u001b[0m\n\u001b[0;32m     85\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mbson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mdbref\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m DBRef\n\u001b[0;32m     86\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mbson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mdecimal128\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Decimal128\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mbson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01merrors\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (InvalidBSON,\n\u001b[0;32m     88\u001b[0m                          InvalidDocument,\n\u001b[1;32m---> 89\u001b[0m                          InvalidStringData)\n\u001b[0;32m     90\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mbson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mint64\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Int64\n\u001b[0;32m     91\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mbson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmax_key\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m MaxKey\n",
      "\u001b[1;31mImportError\u001b[0m: cannot import name 'UuidRepresentation' from 'bson.binary' (c:\\Users\\keshg\\anaconda3\\Lib\\site-packages\\bson\\binary.py)"
     ]
    }
   ],
   "source": [
    "from pymongo import MongoClient\n",
    "import ssl\n",
    "\n",
    "# MongoDB connection URI\n",
    "uri = \"mongodb+srv://mamkeshgautam:QRLkli4G6c1gtkvX@cluster0.c1kdogf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0\"\n",
    "\n",
    "# Create a new client and connect to the server\n",
    "client = MongoClient(uri, ssl=True, ssl_cert_reqs=ssl.CERT_NONE)\n",
    "\n",
    "# Send a ping to confirm a successful connection\n",
    "try:\n",
    "    client.admin.command('ping')\n",
    "    print(\"Pinged your deployment. You successfully connected to MongoDB!\")\n",
    "except Exception as e:\n",
    "    print(f\"An error occurred: {e}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "cannot import name 'UuidRepresentation' from 'bson.binary' (c:\\Users\\keshg\\anaconda3\\Lib\\site-packages\\bson\\binary.py)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[15], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmongo_client\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m MongoClient\n",
      "File \u001b[1;32mc:\\Users\\keshg\\anaconda3\\Lib\\site-packages\\pymongo\\__init__.py:90\u001b[0m\n\u001b[0;32m     82\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmongo_replica_set_client\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m MongoReplicaSetClient\n\u001b[0;32m     83\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01moperations\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (IndexModel,\n\u001b[0;32m     84\u001b[0m                                 InsertOne,\n\u001b[0;32m     85\u001b[0m                                 DeleteOne,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     88\u001b[0m                                 UpdateMany,\n\u001b[0;32m     89\u001b[0m                                 ReplaceOne)\n\u001b[1;32m---> 90\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mread_preferences\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ReadPreference\n\u001b[0;32m     91\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mwrite_concern\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m WriteConcern\n\u001b[0;32m     93\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mhas_c\u001b[39m():\n",
      "File \u001b[1;32mc:\\Users\\keshg\\anaconda3\\Lib\\site-packages\\pymongo\\collection.py:38\u001b[0m\n\u001b[0;32m     36\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mchange_stream\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m ChangeStream\n\u001b[0;32m     37\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcursor\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Cursor, RawBatchCursor\n\u001b[1;32m---> 38\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01merrors\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (BulkWriteError,\n\u001b[0;32m     39\u001b[0m                             ConfigurationError,\n\u001b[0;32m     40\u001b[0m                             InvalidName,\n\u001b[0;32m     41\u001b[0m                             OperationFailure)\n\u001b[0;32m     42\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mhelpers\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (_check_write_command_response,\n\u001b[0;32m     43\u001b[0m                              _raise_last_error)\n\u001b[0;32m     44\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mpymongo\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmessage\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m _UNICODE_REPLACE_CODEC_OPTIONS\n",
      "File \u001b[1;32mc:\\Users\\keshg\\anaconda3\\Lib\\site-packages\\bson\\__init__.py:89\u001b[0m\n\u001b[0;32m     85\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mbson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mdbref\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m DBRef\n\u001b[0;32m     86\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mbson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mdecimal128\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Decimal128\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mbson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01merrors\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m (InvalidBSON,\n\u001b[0;32m     88\u001b[0m                          InvalidDocument,\n\u001b[1;32m---> 89\u001b[0m                          InvalidStringData)\n\u001b[0;32m     90\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mbson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mint64\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m Int64\n\u001b[0;32m     91\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mbson\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmax_key\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m MaxKey\n",
      "\u001b[1;31mImportError\u001b[0m: cannot import name 'UuidRepresentation' from 'bson.binary' (c:\\Users\\keshg\\anaconda3\\Lib\\site-packages\\bson\\binary.py)"
     ]
    }
   ],
   "source": [
    "from pymongo.mongo_client import MongoClient"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "\n",
    "uri = \"mongodb+srv://mamkeshgautam:QRLkli4G6c1gtkvX@cluster0.c1kdogf.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0\"\n",
    "\n",
    "# Create a new client and connect to the server\n",
    "client = MongoClient(uri)\n",
    "\n",
    "# # Send a ping to confirm a successful connection\n",
    "# try:\n",
    "#     client.admin.command('ping')\n",
    "#     print(\"Pinged your deployment. You successfully connected to MongoDB!\")\n",
    "# except Exception as e:\n",
    "#     print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
